## Lab6.Pandas data cleaning Part-II

### 225229138

### Label encoder in Scikit Learn

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
le = LabelEncoder()
#New object
df = pd.DataFrame(data = {'col1': ['foo','bar','foo','bar'],
'col2': ['x', 'y', 'x', 'z'],
'col3': [1, 2, 3, 4]})

In [3]:
df.apply(le.fit_transform)

col1  col2  col3
0     1     0     0
1     0     1     1
2     1     0     2
3     0     2     3

### One Hot Encoder

In [4]:
df=pd.DataFrame({'A':['a','b','a'],'B':['b','a','c'],'C':[1,2,3]})
df

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [5]:
pd.get_dummies(df,prefix=['col1','col2'])

C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1       1       0       0       1       0
1  2       0       1       1       0       0
2  3       1       0       0       0       1

### MinMaxScaler

In [6]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler=MinMaxScaler(feature_range=(0,1))
df2=pd.DataFrame({"col1":[5,-41,-67],"col2":[23,-53,-36],"col3":[-25,10,17]})
mm_scaler.fit_transform(df2)

array([[1.        , 1.        , 0.        ],
       [0.36111111, 0.        , 0.83333333],
       [0.        , 0.22368421, 1.        ]])

### Binarizer

In [7]:
from sklearn.preprocessing import Binarizer
dfb=pd.DataFrame({"col1":[110,200],"col2":[120,800],"col3":[310,400]})
bin=Binarizer(threshold=300)
bin.fit_transform(dfb)

array([[0, 0, 1],
       [0, 1, 1]], dtype=int64)

### Imputer

In [8]:
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
imp_mean=SimpleImputer(missing_values=np.nan,strategy='mean')
df=pd.DataFrame({"col1":[7,2,3],
                  "col2":[4,np.nan,6],
                  "col3":[np.nan,np.nan,3],
                  "col4":[10,np.nan,9] })
print(df)
imp_mean.fit_transform(df)


   col1  col2  col3  col4
0     7   4.0   NaN  10.0
1     2   NaN   NaN   NaN
2     3   6.0   3.0   9.0


array([[ 7. ,  4. ,  3. , 10. ],
       [ 2. ,  5. ,  3. ,  9.5],
       [ 3. ,  6. ,  3. ,  9. ]])

### De-dupliation or Entity Resolution and String Matching

In [9]:
import warnings 
warnings.filterwarnings('ignore') 

In [10]:
pip install fuzzywuzzy

Note: you may need to restart the kernel to use updated packages.


In [11]:
from fuzzywuzzy import fuzz 
from fuzzywuzzy import process 

In [12]:
pip install --upgrade pip 

Note: you may need to restart the kernel to use updated packages.


In [13]:
a="Welcome to Bishop Heber College" 
b="I am pursuing master of DataScience at Bishop collage" 
ratio=fuzz.ratio(a,b) 
weighted_ratio=fuzz.WRatio(a,b) 
unicode_ratio=fuzz.UQRatio(a,b) 

In [14]:
print("Ratio : ", ratio) 

Ratio :  43


In [15]:
print("Weighted Ration:",weighted_ratio) 

Weighted Ration: 86


In [16]:
print("Unicode_ratio : ", unicode_ratio) 

Unicode_ratio :  45


In [17]:
c=a+b 

In [18]:
ex_tract=process.extract('I',c)

In [19]:
ex_tract

[('i', 100), ('I', 100), ('i', 100), ('i', 100), ('i', 100)]

In [23]:
ex_tract1=process.extractOne ("I",c) 
ex_tract1 

('i', 100)

### Dedupe

In [24]:
!pip install dedupe

     --------------------------------------- 96.8/96.8 kB 98.9 kB/s eta 0:00:00
     -------------------------------------- 992.8/992.8 kB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 95.2/95.2 kB 1.8 MB/s eta 0:00:00
     -------------------------------------- 157.1/157.1 kB 2.3 MB/s eta 0:00:00
     -------------------------------------- 184.9/184.9 kB 1.4 MB/s eta 0:00:00
     -------------------------------------- 54.4/54.4 kB 401.1 kB/s eta 0:00:00


In [25]:
dupes=["ftti","rtrt","Dereana","Rereri","Derea","Naereini","Nerea","Jeeee","Dwea","Sawawi"]
process.dedupe(dupes,threshold=10)

dict_keys(['Naereini'])

In [26]:
extract=process.extract("ni",dupes,limit=3)
extract

[('Naereini', 90), ('ftti', 45), ('Dereana', 45)]

In [27]:
extract1=process.extractOne("pri",dupes)
extract1

('Rereri', 60)