# Red Wine Quality Analysis using Numpy Part-I

# 225229138-Sowmiya B

# import modules for numpy

In [1]:
import numpy as np

In [2]:
wines=np.genfromtxt("winequality-red.csv",delimiter=';',skip_header=1)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [3]:
wines.shape

(1599, 12)

In [4]:
wines.shape[0]

1599

In [5]:
wines.shape[1]

12

In [6]:
wines.ndim

2

In [7]:
type(wines)

numpy.ndarray

In [8]:
wines.dtype

dtype('float64')

In [9]:
wines[:5]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

In [10]:
wines[2][3]

2.3

In [11]:
wines[:3,3]

array([1.9, 2.6, 2.3])

In [12]:
wines[::,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [13]:
wines[1,::]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [14]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

In [15]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [16]:
#updated
wines[0,0]=100
wines[0,0]

100.0

In [17]:
wines[0,0]=7.4

In [18]:
x=wines[3,:]
x

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [19]:
x[1]

0.28

In [20]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

# Vectorization Operations

In [21]:
wines[::,11]

array([5., 5., 5., ..., 6., 5., 6.])

In [22]:
a=wines[::,11]+10
a

array([15., 15., 15., ..., 16., 15., 16.])

In [23]:
wines[::,10]

array([ 9.4,  9.8,  9.8, ..., 11. , 10.2, 11. ])

In [24]:
b=wines[::,10]*3
b

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

In [25]:
c=a+a
c

array([30., 30., 30., ..., 32., 30., 32.])

In [26]:
d=a*b
d

array([423., 441., 441., ..., 528., 459., 528.])

# Broadcasting

In [27]:
rand_array=np.random.random((12))

In [28]:
rand_array

array([0.52255496, 0.48858895, 0.17798493, 0.8549481 , 0.74662184,
       0.05105011, 0.95415805, 0.23953992, 0.95819656, 0.62126708,
       0.67900312, 0.13250223])

In [29]:
wines+rand_array

array([[ 7.92255496,  1.18858895,  0.17798493, ...,  1.18126708,
        10.07900312,  5.13250223],
       [ 8.32255496,  1.36858895,  0.17798493, ...,  1.30126708,
        10.47900312,  5.13250223],
       [ 8.32255496,  1.24858895,  0.21798493, ...,  1.27126708,
        10.47900312,  5.13250223],
       ...,
       [ 6.82255496,  0.99858895,  0.30798493, ...,  1.37126708,
        11.67900312,  6.13250223],
       [ 6.42255496,  1.13358895,  0.29798493, ...,  1.33126708,
        10.87900312,  5.13250223],
       [ 6.52255496,  0.79858895,  0.64798493, ...,  1.28126708,
        11.67900312,  6.13250223]])