# DVA - LAB-2 -Wine Quality Analytics Numpy Part-II

### 225229138-B.Sowmiya

In [1]:
import numpy as np

In [2]:
wines=np.genfromtxt('winequality-red (1).csv',delimiter=';',skip_header=1)

# NUMPY AGGREGATION METHODS

### Find the sum of all residual sugar values

In [3]:
wines[:,3].sum()

4059.55

### Find sums of every feature value. there are 12 features altogether

In [4]:
sum(wines)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

### Find sum of every row

In [5]:
t=wines.sum(axis=1)
t

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

### What is its size

In [6]:
wines.shape

(1599, 12)

### What is the maximum residual sugar values in red wine data¶

In [7]:
t=wines[:,3]
t=t.astype(int)
t

array([1, 2, 2, ..., 2, 2, 3])

### Find its maximum residual sugar value

In [8]:
t=wines[:,3].max()
t=t.astype(int)
t

15

### Find its minimum residual sugar value in red wines data?

In [9]:
t=wines[:,3].min()
t=t.astype(int)
t

0

### What is the average residual sugar value in red wines data?

In [10]:
t=wines[:,3].mean()
t

2.53880550343965

### What is 25 percentile residual sugar value ?

In [11]:
np.percentile(wines[:,3],25)

1.9

### What is 75 percentile residual sugar value ?

In [12]:
np.percentile(wines[:,3],75)

2.6

### Find the average of each feature value

In [13]:
wines.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

# NUMPY ARRAY COMPARISONS

In [14]:
wines[:,-1]>5

array([False, False, False, ...,  True, False,  True])

In [15]:
wines[:,-1]>7

array([False, False, False, ..., False, False, False])

In [16]:
t=wines[:,-1]>7
True in t

True

In [17]:
high_quality = wines[:,-1]>7
high_quality

array([False, False, False, ..., False, False, False])

In [18]:
wines[high_quality][0:3]

array([[7.900e+00, 3.500e-01, 4.600e-01, 3.600e+00, 7.800e-02, 1.500e+01,
        3.700e+01, 9.973e-01, 3.350e+00, 8.600e-01, 1.280e+01, 8.000e+00],
       [1.030e+01, 3.200e-01, 4.500e-01, 6.400e+00, 7.300e-02, 5.000e+00,
        1.300e+01, 9.976e-01, 3.230e+00, 8.200e-01, 1.260e+01, 8.000e+00],
       [5.600e+00, 8.500e-01, 5.000e-02, 1.400e+00, 4.500e-02, 1.200e+01,
        8.800e+01, 9.924e-01, 3.560e+00, 8.200e-01, 1.290e+01, 8.000e+00]])

In [19]:
t = (wines[:,-1]>7)&(wines[:,-2]>10)
t

array([False, False, False, ..., False, False, False])

In [20]:
wines[t,10:]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

# Combining NumPy Arrays

### Combine red wine and white wine data

### Open white wine dataset

In [22]:
white_wines = np.genfromtxt('winequality-white.csv',delimiter=';',skip_header=1)

### Show size of white_wines

### combine wines and white_wines data frames using vstack and call it all_wines

In [23]:
wines=np.vstack((wines,white_wines))

In [24]:
wines.shape

(6497, 12)

### Combine wines and white_wines data frames using concatenate method

In [25]:
wines1 = np.concatenate((wines,white_wines),axis=0)

In [26]:
wines1.shape

(11395, 12)

# Matrix Operations and Reshape

### Find Transpose of wines and print its size

In [27]:
t=wines.T
t.shape

(12, 6497)

### Convert wines data into 1D array


In [28]:
wines.ravel()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.32, 11.8 ,  6.  ])

In [29]:
wines.ravel().shape

(77964,)

### Reshape second row of wines into a 2-dimensional array with 2 rows and 6 columns

In [30]:
wines[1].reshape((2,6))

array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]])

# Sort alcohol column Ascending Order


In [31]:
sorted_alcohol=np.sort(wines[:,-2])

In [32]:
sorted_alcohol

array([ 8.  ,  8.  ,  8.4 , ..., 14.05, 14.2 , 14.9 ])

### Make sorting to take place in-place


In [33]:
wines[:,-2].sort()

In [34]:
wines[:,-2]

array([ 8.  ,  8.  ,  8.4 , ..., 14.05, 14.2 , 14.9 ])

### Sort alcohol column Descending Order

In [35]:
sorted_alcohol_desc=np.sort(wines[:,10])[::-1]

In [36]:
sorted_alcohol_desc

array([14.9 , 14.2 , 14.05, ...,  8.4 ,  8.  ,  8.  ])

### Will original data be modified?. Check top 10 rows

In [37]:
wines[:,-2]

array([ 8.  ,  8.  ,  8.4 , ..., 14.05, 14.2 , 14.9 ])